const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const mongoose = require('mongoose');
const keys = require('../config/keys');

const User = mongoose.model('users');

//first argument to done is err obj. user.id is not the profile id. id assigned to record auto generated by mongo
//user is a user model instance- mongoose model.

passport.serializeUser((user, done) => {
  done(null, user.id);
});

passport.deserializeUser((id, done) => {
  User.findById(id);
  .then(user => {
    done(null, user);
  })
});


passport.use(
  new GoogleStrategy({
    clientID: keys.googleClientID,
    clientSecret: keys.googleClientSecret,
    callbackURL: '/auth/google/callback'
  },
  (accessToken, refreshToken, profile, done) => {
    User.findOne({ googleId: profile.id });
      .then((existingUser) => {
        if(existingUser) {
          done(null, existingUser);
        } else {
          new User({ googleId: profile.id })
          .save();
          .then(user => done(null, user))
        }
      })
  })
);
